### PR TITLE
Initial Version

### PR DESCRIPTION
**Pull request by steelbrain**
Configurations removed from base linter

 - [x] showErrorInline
 - [ ] ~~inlineTooltipInterval~~
 - [ ] ~~gutterEnabled~~
 - [x] gutterPosition
 - [x] underlineIssues
 - [x] showErrorPanel
 - [ ] ~~displayLinterInfo~~
 - [ ] ~~displayLinterStatus~~
 - [ ] ~~showErrorTabLine~~
 - [ ] ~~showErrorTabFile~~
 - [ ] ~~showErrorTabProject~~
 - [ ] ~~statusIconScope~~
 - [ ] ~~statusIconPosition~~

### CODE REVIEW

**Comment by steelbrain** [comment]
@simurai does CSS has a transition that allows for smooth increase in height when an element is appended to the container?

**Comment by simurai** [comment]
> does CSS has a transition that allows for smooth increase in height when an element is appended to the container?

Not in an easy way if the height is using `auto`. It might can be hacked with animating `min-height`. Is for something like the gif in https://github.com/atom/notifications/blob/master/README.md.

**Comment by steelbrain** [comment]
Thew new `Message` class supports `HTMLElement` caching, means we will no longer be giving non-used messages as garbage and creating them when we need new ones. DOM operations are cpu-intensive, therefore we'd be keeping them at disposal and using them when necessary. Currently the max number is a hard-coded 250, but it won't be much complicated to get average number of insertions of the last ten times and use it as max

**Comment by steelbrain** [comment]
Iteartion `#1` is complete :heart:

**Pull request merged**
